package bean;
// Generated 07/06/2022 15:08:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="vendas_cursos"
)
public class Clientes  implements java.io.Serializable {


     private int idclientes;
     private String nome;
     private String sexo;
     private String rg;
     private String cpf;
     private String telefone;
     private String email;
     private Date dataNascimento;
     private String nacionalidade;
     private String estado;
     private String cidade;
     private String bairro;
     private int escolaridade;
     private String profissao;
     private int idioma;
     

    public Clientes() {
    }

	
    public Clientes(int idclientes) {
        this.idclientes = idclientes;
    }
    public Clientes(int idclientes, String nome, String sexo, String rg, String cpf, String telefone, String email, Date dataNascimento, String nacionalidade, String estado, String cidade, String bairro, Byte escolaridade, String profissao, Byte idioma) {
       this.idclientes = idclientes;
       this.nome = nome;
       this.sexo = sexo;
       this.rg = rg;
       this.cpf = cpf;
       this.telefone = telefone;
       this.email = email;
       this.dataNascimento = dataNascimento;
       this.nacionalidade = nacionalidade;
       this.estado = estado;
       this.cidade = cidade;
       this.bairro = bairro;
       this.escolaridade = escolaridade;
       this.profissao = profissao;
       this.idioma = idioma;
    }
   
     @Id 

    
    @Column(name="idclientes", unique=true, nullable=false)
    public int getIdclientes() {
        return this.idclientes;
    }
    
    public void setIdclientes(int idclientes) {
        this.idclientes = idclientes;
    }

    
    @Column(name="nome", length=30)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sexo", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="rg", length=9)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="cpf", length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="telefone", length=15)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento", length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="nacionalidade", length=15)
    public String getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }

    
    @Column(name="estado", length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="cidade", length=30)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="bairro", length=30)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="escolaridade")
    public int getEscolaridade() {
        return this.escolaridade;
    }
    
    public void setEscolaridade(int escolaridade) {
        this.escolaridade = escolaridade;
    }

    
    @Column(name="profissao", length=50)
    public String getProfissao() {
        return this.profissao;
    }
    
    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }

    
    @Column(name="idioma")
    public int getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(int idioma) {
        this.idioma = idioma;
    }
    
    public String toString(){
        return this.getNome();
    }
    
    public boolean equals(Object object){
        if(object instanceof Clientes){
            Clientes clientes = (Clientes) object;
            if(this.idclientes == clientes.idclientes){
                return true;
            }
        }
        return false;
    }
}


