package bean;
// Generated 07/06/2022 15:08:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cursos generated by hbm2java
 */
@Entity
@Table(name="cursos"
    ,catalog="vendas_cursos"
)
public class Cursos  implements java.io.Serializable {


     private int idcursos;
     private Professores professores;
     private String nome;
     private int duracao;
     private String certificado;
     private int nivel;
     private double valorUnitario;
     private int modulos;

    public Cursos() {
    }

	
    public Cursos(int idcursos) {
        this.idcursos = idcursos;
    }
    public Cursos(int idcursos, Professores professores, String nome, int duracao, String certificado, Byte nivel, double valorUnitario, int modulos) {
       this.idcursos = idcursos;
       this.professores = professores;
       this.nome = nome;
       this.duracao = duracao;
       this.certificado = certificado;
       this.nivel = nivel;
       this.valorUnitario = valorUnitario;
       this.modulos = modulos;
    }
   
     @Id 

    
    @Column(name="idcursos", unique=true, nullable=false)
    public int getIdcursos() {
        return this.idcursos;
    }
    
    public void setIdcursos(int idcursos) {
        this.idcursos = idcursos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="professor")
    public Professores getProfessores() {
        return this.professores;
    }
    
    public void setProfessores(Professores professores) {
        this.professores = professores;
    }

    
    @Column(name="nome", length=30)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="duracao")
    public int getDuracao() {
        return this.duracao;
    }
    
    public void setDuracao(int duracao) {
        this.duracao = duracao;
    }

    
    @Column(name="certificado", length=1)
    public String getCertificado() {
        return this.certificado;
    }
    
    public void setCertificado(String certificado) {
        this.certificado = certificado;
    }

    
    @Column(name="nivel")
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="valor_unitario", precision=10)
    public double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    
    @Column(name="modulos")
    public int getModulos() {
        return this.modulos;
    }
    
    public void setModulos(int modulos) {
        this.modulos = modulos;
    }
    
    public String toString(){
        return this.getNome();
    }
}


