package bean;
// Generated 07/06/2022 15:08:41 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="vendas_cursos"
)
public class Usuarios  implements java.io.Serializable {


     private int idusuarios;
     private String nome;
     private String apelido;
     private String cpf;
     private String senha;
     private int nivel;
     private String ativo;
     private Date dataNascimento;

    public Usuarios() {
    }

	
    public Usuarios(int idusuarios) {
        this.idusuarios = idusuarios;
    }
    public Usuarios(int idusuarios, String nome, String apelido, String cpf, String senha, Byte nivel, String ativo, Date dataNascimento) {
       this.idusuarios = idusuarios;
       this.nome = nome;
       this.apelido = apelido;
       this.cpf = cpf;
       this.senha = senha;
       this.nivel = nivel;
       this.ativo = ativo;
       this.dataNascimento = dataNascimento;
    }
   
     @Id 

    
    @Column(name="idusuarios", unique=true, nullable=false)
    public int getIdusuarios() {
        return this.idusuarios;
    }
    
    public void setIdusuarios(int idusuarios) {
        this.idusuarios = idusuarios;
    }

    
    @Column(name="nome", length=30)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="apelido", length=20)
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }

    
    @Column(name="cpf", length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="senha", length=45)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="nivel")
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="ativo", length=1)
    public String getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(String ativo) {
        this.ativo = ativo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento", length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String toString(){
        return this.getNome();
    }
    
    public boolean equals(Object object){
        
            if(object instanceof Usuarios){
                Usuarios usuario = (Usuarios) object;
                if(this.getIdusuarios() == usuario.getIdusuarios()){
                    return true;
                }
            }
        return false;
    }
}


