package bean;
// Generated 07/06/2022 15:08:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vendascursos generated by hbm2java
 */
@Entity
@Table(name="vendascursos"
    ,catalog="vendas_cursos"
)
public class Vendascursos  implements java.io.Serializable {


     private VendascursosId id;
     private Cursos cursos;
     private Vendas vendas;
     private double valorUnitario;
     private double total;
     private int quantidadeModulos;

    public Vendascursos() {
    }

	
    public Vendascursos(VendascursosId id, Cursos cursos, Vendas vendas) {
        this.id = id;
        this.cursos = cursos;
        this.vendas = vendas;
    }
    public Vendascursos(VendascursosId id, Cursos cursos, Vendas vendas, double valorUnitario, double total, Byte quantidadeModulos) {
       this.id = id;
       this.cursos = cursos;
       this.vendas = vendas;
       this.valorUnitario = valorUnitario;
       this.total = total;
       this.quantidadeModulos = quantidadeModulos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idvendas", column=@Column(name="idvendas", nullable=false) ), 
        @AttributeOverride(name="curso", column=@Column(name="curso", nullable=false) ) } )
    public VendascursosId getId() {
        return this.id;
    }
    
    public void setId(VendascursosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="curso", nullable=false, insertable=false, updatable=false)
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idvendas", nullable=false, insertable=false, updatable=false)
    public Vendas getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Vendas vendas) {
        this.vendas = vendas;
    }

    
    @Column(name="valor_unitario", precision=10)
    public double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    
    @Column(name="total", precision=10)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

    
    @Column(name="quantidade_modulos")
    public int getQuantidadeModulos() {
        return this.quantidadeModulos;
    }
    
    public void setQuantidadeModulos(int quantidadeModulos) {
        this.quantidadeModulos = quantidadeModulos;
    }

    public String toString(){
        return this.cursos.getNome();
    }
    
    public boolean equals(Object object){
        if(object instanceof Vendascursos){
            Vendascursos vendascursos = (Vendascursos) object;
            if(this.id.getCurso() == vendascursos.id.getCurso()){
                return true;
            }
        }
        return false;
    }
}


