package bean;
// Generated 07/06/2022 15:08:41 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendascursosId generated by hbm2java
 */
@Embeddable
public class VendascursosId  implements java.io.Serializable {


     private int idvendas;
     private int curso;

    public VendascursosId() {
    }

    public VendascursosId(int idvendas, int curso) {
       this.idvendas = idvendas;
       this.curso = curso;
    }
   


    @Column(name="idvendas", nullable=false)
    public int getIdvendas() {
        return this.idvendas;
    }
    
    public void setIdvendas(int idvendas) {
        this.idvendas = idvendas;
    }


    @Column(name="curso", nullable=false)
    public int getCurso() {
        return this.curso;
    }
    
    public void setCurso(int curso) {
        this.curso = curso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendascursosId) ) return false;
		 VendascursosId castOther = ( VendascursosId ) other; 
         
		 return (this.getIdvendas()==castOther.getIdvendas())
 && (this.getCurso()==castOther.getCurso());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdvendas();
         result = 37 * result + this.getCurso();
         return result;
   }   


}


